/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as DashboadIndexRouteImport } from './routes/dashboad/index'
import { Route as EventsAnsewerIndexRouteImport } from './routes/events/ansewer/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboadIndexRoute = DashboadIndexRouteImport.update({
  id: '/dashboad/',
  path: '/dashboad/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsAnsewerIndexRoute = EventsAnsewerIndexRouteImport.update({
  id: '/events/ansewer/',
  path: '/events/ansewer/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboad/': typeof DashboadIndexRoute
  '/events/': typeof EventsIndexRoute
  '/events/ansewer/': typeof EventsAnsewerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboad': typeof DashboadIndexRoute
  '/events': typeof EventsIndexRoute
  '/events/ansewer': typeof EventsAnsewerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboad/': typeof DashboadIndexRoute
  '/events/': typeof EventsIndexRoute
  '/events/ansewer/': typeof EventsAnsewerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboad/' | '/events/' | '/events/ansewer/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboad' | '/events' | '/events/ansewer'
  id: '__root__' | '/' | '/dashboad/' | '/events/' | '/events/ansewer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboadIndexRoute: typeof DashboadIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  EventsAnsewerIndexRoute: typeof EventsAnsewerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboad/': {
      id: '/dashboad/'
      path: '/dashboad'
      fullPath: '/dashboad/'
      preLoaderRoute: typeof DashboadIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/ansewer/': {
      id: '/events/ansewer/'
      path: '/events/ansewer'
      fullPath: '/events/ansewer/'
      preLoaderRoute: typeof EventsAnsewerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboadIndexRoute: DashboadIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  EventsAnsewerIndexRoute: EventsAnsewerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
